
FROM php:5.6-apache

ENV QA_CONFIG /var/www/html/qa-config.php

RUN apt-get update \
        && apt-get install -y --no-install-recommends \
             unzip \
             git   \
        && rm -r /var/lib/apt/lists/*